version: '3.1'
services:
  odoo15:
    build: .
    image: odoo:15Custom
    depends_on:
      - mydb
    ports:
      - "8049:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./community:/mnt/enterprise
      # #- ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      # - ./project/nama_project:/mnt/extra-addons
      #- ./doc:/mnt/enterprise
      - ./etc:/etc/odoo
    restart: always
    # command: -u 

  pgadmin:
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: 1
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: always
